version: '3'

services:

  testrunner:
    build:
      context: .
    environment:
      HUB_HOST: hub:4444
    volumes:
      - .:/usr/src/app
    links:
      - hub

  hub:
    image: selenium/hub:3.13.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      GRID_BROWSER_TIMEOUT: 10000 # 10 seconds
      GRID_TIMEOUT: 10000
      VIRTUAL_HOST: selenium.hub.docker
    ports:
      - "4444:4444"

  node-firefox:
    image: selenium/node-firefox:3.13.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment: &SELENIUM_NODE_ENV
      # this is a necessary workaround due to a known bug
      # https://github.com/SeleniumHQ/docker-selenium/issues/133
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - "0:5900"
    links:
      - hub

  node-chrome:
    image: selenium/node-chrome:3.13.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5901:5900"
    links:
      - hub

  node-chrome-debug:
    image: selenium/node-chrome-debug:3.13.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5900:5900"
    links:
      - hub

  node-firefox-debug:
    image: selenium/node-firefox-debug:3.13.0 # this version should match that of the selenium-webdriver gem (see Gemfile)
    environment:
      <<: *SELENIUM_NODE_ENV
    ports:
      - "5901:5900"
    links:
      - hub
